// export const religions = ["Muslim", "Hindu", "Christian", "Sikh", "Parsi", "Jain", "Buddhist", "Jewish", "Atheist", "Spiritual", "Other"];

export const religions = [
  "Islam",
  "Christianity",
  "Hinduism",
  "Judaism",
  "Buddhism",
  "Others",
];

export const motherTongues = [
  "Abkhazian",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Assamese",
  "Avaric",
  "Avestan",
  "Aymara",
  "Azerbaijani",
  "Bambara",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bihari",
  "Bislama",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Catalan",
  "Chamorro",
  "Chechen",
  "Chichewa",
  "Chinese",
  "Chuvash",
  "Cornish",
  "Corsican",
  "Cree",
  "Croatian",
  "Czech",
  "Danish",
  "Divehi",
  "Dutch",
  "Dzongkha",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Faroese",
  "Fijian",
  "Finnish",
  "French",
  "Frisian",
  "Fulah",
  "Galician",
  "Ganda",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Hausa",
  "Hebrew",
  "Herero",
  "Hindi",
  "Hiri Motu",
  "Hungarian",
  "Icelandic",
  "Ido",
  "Igbo",
  "Indonesian",
  "Interlingua",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kanuri",
  "Kashmiri",
  "Kazakh",
  "Kikuyu",
  "Kinyarwanda",
  "Kirghiz",
  "Komi",
  "Kongo",
  "Korean",
  "Kurdish",
  "Lao",
  "Latin",
  "Latvian",
  "Limburgish",
  "Lingala",
  "Lithuanian",
  "Luba-Katanga",
  "Luxembourgish",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Manx",
  "Maori",
  "Marathi",
  "Marshallese",
  "Mongolian",
  "Nauru",
  "Navajo",
  "Nepali",
  "North Ndebele",
  "Northern Sami",
  "Norwegian",
  "Norwegian Bokmål",
  "Norwegian Nynorsk",
  "Occitan",
  "Ojibwa",
  "Oriya",
  "Oromo",
  "Ossetian",
  "Pali",
  "Panjabi",
  "Pashto",
  "Persian",
  "Polish",
  "Portuguese",
  "Pushto",
  "Quechua",
  "Romanian",
  "Russian",
  "Samoan",
  "Sango",
  "Sanskrit",
  "Sardinian",
  "Scottish Gaelic",
  "Serbian",
  "Shona",
  "Sichuan Yi",
  "Sindhi",
  "Sinhalese",
  "Slovak",
  "Slovenian",
  "Somali",
  "Sotho",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swati",
  "Swedish",
  "Tagalog",
  "Tahitian",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Tonga",
  "Tsonga",
  "Tswana",
  "Turkish",
  "Turkmen",
  "Twi",
  "Uighur",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Venda",
  "Vietnamese",
  "Volapük",
  "Walloon",
  "Welsh",
  "Western Frisian",
  "Wolof",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zhuang",
  "Zulu",
];

export const communities = [
  "Abkhazian",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Assamese",
  "Avaric",
  "Avestan",
  "Aymara",
  "Azerbaijani",
  "Bambara",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bihari",
  "Bislama",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Catalan",
  "Chamorro",
  "Chechen",
  "Chichewa",
  "Chinese",
  "Chuvash",
  "Cornish",
  "Corsican",
  "Cree",
  "Croatian",
  "Czech",
  "Danish",
  "Divehi",
  "Dutch",
  "Dzongkha",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Faroese",
  "Fijian",
  "Finnish",
  "French",
  "Frisian",
  "Fulah",
  "Galician",
  "Ganda",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Hausa",
  "Hebrew",
  "Herero",
  "Hindi",
  "Hiri Motu",
  "Hungarian",
  "Icelandic",
  "Ido",
  "Igbo",
  "Indonesian",
  "Interlingua",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kanuri",
  "Kashmiri",
  "Kazakh",
  "Kikuyu",
  "Kinyarwanda",
  "Kirghiz",
  "Komi",
  "Kongo",
  "Korean",
  "Kurdish",
  "Lao",
  "Latin",
  "Latvian",
  "Limburgish",
  "Lingala",
  "Lithuanian",
  "Luba-Katanga",
  "Luxembourgish",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Manx",
  "Maori",
  "Marathi",
  "Marshallese",
  "Mongolian",
  "Nauru",
  "Navajo",
  "Nepali",
  "North Ndebele",
  "Northern Sami",
  "Norwegian",
  "Norwegian Bokmål",
  "Norwegian Nynorsk",
  "Occitan",
  "Ojibwa",
  "Oriya",
  "Oromo",
  "Ossetian",
  "Pali",
  "Panjabi",
  "Pashto",
  "Persian",
  "Polish",
  "Portuguese",
  "Pushto",
  "Quechua",
  "Romanian",
  "Russian",
  "Samoan",
  "Sango",
  "Sanskrit",
  "Sardinian",
  "Scottish Gaelic",
  "Serbian",
  "Shona",
  "Sichuan Yi",
  "Sindhi",
  "Sinhalese",
  "Slovak",
  "Slovenian",
  "Somali",
  "Sotho",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swati",
  "Swedish",
  "Tagalog",
  "Tahitian",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Tonga",
  "Tsonga",
  "Tswana",
  "Turkish",
  "Turkmen",
  "Twi",
  "Uighur",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Venda",
  "Vietnamese",
  "Volapük",
  "Walloon",
  "Welsh",
  "Western Frisian",
  "Wolof",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zhuang",
  "Zulu",
];
// export const profileFor = ["Self", "Son", "Daughter", "Brother", "Sister", "Friend", "Relative"]
export const profileFor = [
  "Myself",
  "My Son",
  "My Daughter",
  "My Brother",
  "My Sister",
  "My Friend",
  "My Relative",
];

// export const cities = ["Dhaka", "Chittagon", "Cumilla", "Sylet", "Barishal"]

export const cities = [
  "Dhaka North",
  "Dhaka South",
  "Chittagong",
  "Khulna",
  "Bogura",
  "Sylhet",
  "Rajshahi",
  "Comilla",
  "Barisal",
  "Rangpur",
  "Mymensingh",
  "Gazipur",
  "Narayanganj",
  "New York",
  "Los Angeles",
  "Chicago",
  "Washington D.C.",
  "Boston",
  "El Paso",
  "Detroit",
  "Nashville",
  "Memphis",
  "Oklahoma City",
  "Las Vegas",
  "Louisville",
  "Baltimore",
  "Atlanta",
  "Long Beach",
  "Omaha",
  "Raleigh",
  "Colorado Springs",
  "Miami",
  "Virginia Beach",
  "Oakland",
];

// export const recidencies = ["Bangladeshi", "Indian", "American"]
export const recidencies = [
  "Citizen",
  "Permanent Resident",
  "Student Visa",
  "Temporary Visa",
  "Work Permit",
];

export const maritalStatuses = [
  "Never Married",
  "Married",
  "Divorced",
  "Widowed",
  "Awaiting Divorce",
];

// export const heights = ["5ft 1nc - 154cm", "5ft 2nc - 157cm", "5ft 3nc - 160cm"]

// export const heights = ["4ft 5in - 134cm",
//     "4ft 6in - 137cm",
//     "4ft 7in - 139cm",
//     "4ft 9in - 142cm",
//     "4ft 10in - 144cm",
//     "4ft 11in - 147cm",
//     "5ft - 152cm",
//     "5ft 1in - 154cm",
//     "5ft 2in - 157cm",
//     "5ft 3in - 160cm",
//     "5ft 4in - 162cm",
//     "5ft 5in - 165cm",
//     "5ft 6in - 167cm",
//     "5ft 7in - 170cm",
//     "5ft 8in - 172cm",
//     "5ft 9in - 175cm",
//     "5ft 10in - 177cm",
//     "5ft 11in - 180cm",
//     "6ft - 182cm",
//     "6ft 1in - 185cm",
//     "6ft 2in - 187cm",
//     "6ft 3in - 190cm",
//     "6ft 4in - 193cm",
//     "6ft 5in - 195cm",
//     "6ft 6in - 198cm",
//     "6ft 7in - 200cm",
//     "6ft 8in - 203cm",
//     "6ft 9in - 205cm",
//     "6ft 10in - 208cm",
//     "6ft 11in - 210cm",
//     "7ft - 213cm"]

export const heights = [
  { label: "4ft 5in - 134cm", value: "53" },
  { label: "4ft 6in - 137cm", value: "54" },
  { label: "4ft 7in - 139cm", value: "55" },
  { label: "4ft 9in - 142cm", value: "57" },
  { label: "4ft 10in - 144cm", value: "58" },
  { label: "4ft 11in - 147cm", value: "59" },
  { label: "5ft 1in - 154cm", value: "61" },
  { label: "5ft 2in - 157cm", value: "62" },
  { label: "5ft 3in - 160cm", value: "63" },
  { label: "5ft 4in - 162cm", value: "64" },
  { label: "5ft 5in - 165cm", value: "65" },
  { label: "5ft 6in - 167cm", value: "66" },
  { label: "5ft 7in - 170cm", value: "67" },
  { label: "5ft 8in - 172cm", value: "68" },
  { label: "5ft 9in - 175cm", value: "69" },
  { label: "5ft 10in - 177cm", value: "70" },
  { label: "5ft 11in - 180cm", value: "71" },
  { label: "6ft 1in - 185cm", value: "73" },
  { label: "6ft 2in - 187cm", value: "74" },
  { label: "6ft 3in - 190cm", value: "75" },
  { label: "6ft 4in - 193cm", value: "76" },
  { label: "6ft 5in - 195cm", value: "77" },
  { label: "6ft 6in - 198cm", value: "78" },
  { label: "6ft 7in - 200cm", value: "79" },
  { label: "6ft 8in - 203cm", value: "80" },
  { label: "6ft 9in - 205cm", value: "81" },
  { label: "6ft 10in - 208cm", value: "82" },
  { label: "6ft 11in - 210cm", value: "83" },
];

// export const subCommunities = ["Dhakaya", "NoaKhailla", "Barishalla"]
export const subCommunities = [
  "Shia",
  "Ansari",
  "Pathan",
  "Shafi",
  "Sunni",
  "Sunni Hanafi",
  "Sunni Hunbali",
  "Sunni Maliki",
  "Sunni Shafi",
];

// export const qualifications = ["BSc", "MSc", "BA", "DR", "PhD"]

// export const qualifications = [
//   {
//     group: "ENGINEERING",
//     items: [
//       "B.E/B.Tech",
//       "M.E/M.Tech",
//       "M.S Engineering",
//       "B.Eng (Hons)",
//       "M.Eng (Hons) Engineering Diploma",
//       "AE AET",
//     ],
//   },
//   {
//     group: "ARTS/DESIGN",
//     items: [
//       "B.A",
//       "B.Ed",
//       "BJMC",
//       "BFA",
//       "B.Arch",
//       "B.Des",
//       "BMM",
//       "MFA M.Ed",
//       "M.A",
//       "MSW",
//       "MJMC",
//       "M.Arch M.Des",
//       "BA (Hons)",
//       "B.Arch (Hons)",
//       "DFA",
//       "D.Ed",
//       "D.Arch",
//       "AA",
//       "AFA",
//     ],
//   },

//   {
//     group: "FINANCE/COMMERCE",
//     items: [
//       "B.Com",
//       "CA/CPA",
//       "CFA",
//       "CS",
//       "BSc/BFin",
//       "M.Com",
//       "MSc/MFin / MS",
//       "BCom (Hons)",
//       "PGD Finance",
//     ],
//   },
//   {
//     group: "SCIENCE",
//     items: [
//       "B.Sc",
//       "M.Sc",
//       "BSc (Hons)",
//       "DipSc",
//       "BDS",
//       "BPT",
//       "BAMS",
//       "BHMS",
//       "B.Pharma",
//       "BVSc",
//       "BSN/BScN",
//       "MDS",
//       "MCh",
//       "M.D",
//       "M.S Medicine",
//       "MPT",
//       "DM",
//       "M.Pharma",
//       "MVSc",
//       "MMed",
//       "PGD Medicine",
//       "ADN",
//     ],
//   },
//   {
//     group: "COMPUTERS/IT",
//     items: [
//       "BCA",
//       "B.IT",
//       "BCS",
//       "BA Computer Science",
//       "MCA",
//       "PGDCA",
//       "IT Diploma",
//       "ADIT",
//     ],
//   },

//   {
//     group: "MANAGEMENT",
//     items: ["BBA", "BHM", "BBM", "MBA", "PGDM", "ABA", "ADBus"],
//   },
//   { group: "LAW", items: ["BL/LLB", "ML/LLM", "LLB (Hons)", "ALA"] },
//   { group: "DOCTORATE", items: ["Ph.D", "M.Phil"] },
//   {
//     group: "OTHERS",
//     items: [
//       "Bachelor",
//       "Master",
//       "Diploma",
//       "Honours",
//       "Doctorate",
//       "Associate",
//     ],
//   },
//   { group: "NON-GRADUATE", items: ["High school", "Less than high school"] },
// ];

export const qualifications = [
  "B.A",
  "B.Ed",
  "BJMC",
  "BFA",
  "B.Arch",
  "B.Des",
  "BMM",
  "MFA M.Ed",
  "M.A",
  "MSW",
  "MJMC",
  "M.Arch M.Des",
  "BA (Hons)",
  "B.Arch (Hons)",
  "DFA",
  "D.Ed",
  "D.Arch",
  "AA",
  "AFA",
  "BCA",
  "B.IT",
  "BCS",
  "BA Computer Science",
  "MCA",
  "PGDCA",
  "IT Diploma",
  "ADIT",
  "B.Sc",
  "M.Sc",
  "BSc (Hons)",
  "DipSc",
  "BDS",
  "BPT",
  "BAMS",
  "BHMS",
  "B.Pharma",
  "BVSc",
  "BSN/BScN",
  "MDS",
  "MCh",
  "M.D",
  "M.S Medicine",
  "MPT",
  "DM",
  "M.Pharma",
  "MVSc",
  "MMed",
  "PGD Medicine",
  "ADN",
  "B.Com",
  "CA/CPA",
  "CFA",
  "CS",
  "BSc/BFin",
  "M.Com",
  "MSc/MFin / MS",
  "BCom (Hons)",
  "PGD Finance",
  "B.A",
  "B.Ed",
  "BJMC",
  "BFA",
  "B.Arch",
  "B.Des",
  "BMM",
  "MFA M.Ed",
  "M.A",
  "MSW",
  "MJMC",
  "M.Arch M.Des",
  "BA (Hons)",
  "B.Arch (Hons)",
  "DFA",
  "D.Ed",
  "D.Arch",
  "AA",
  "AFA",
];
// export const worksWiths = ["Private Company", "Government", "Business", "Defense"]
export const worksWiths = [
  "Open to All",
  "Private Company",
  "Government/Public Sector",
  "Defense/Civil Services",
  "Business/Self Employed",
  "Non Working",
];

export const worksWithsOwn = [
  "Private Company",
  "Government/Public Sector",
  "Defense/Civil Services",
  "Business/Self Employed",
  "Non Working",
];

export const professions = [
  "Banking Professional",
  "Chatered Accountant",
  "Software Engineer",
];

// export const incomes = ["Upto BDT 20K monthly", "BDT 20K to 50K monthly", "BDT 50K to 100K monthly"]

// export const incomes = ["Upto USD 40K",
//     "Upto USD 40K - 60K",
//     "Upto USD 60K - 80K",
//     "Upto USD 80K - 100K",
//     "Upto USD 100K - 125K",
//     "Upto USD 125K - 150K",
//     "Upto USD 150K - 175K",
//     "Upto USD 175K - 200K",
//     "Upto USD 200K - 250K",
//     "Upto USD 250K - 300K",
//     "Upto USD 300K - 500K",
//     "Above USD 500K"]

export const incomes = [
  { label: "Upto USD 40K", value: { min: "40", max: "40" } },
  { label: "Upto USD 40K - 60K", value: { min: "40", max: "60" } },
  { label: "Upto USD 60K - 80K", value: { min: "60", max: "80" } },
  { label: "Upto USD 80K - 100K", value: { min: "80", max: "100" } },
  { label: "Upto USD 100K - 125K", value: { min: "100", max: "125" } },
  { label: "Upto USD 125K - 150K", value: { min: "125", max: "150" } },
  { label: "Upto USD 150K - 175K", value: { min: "150", max: "175" } },
  { label: "Upto USD 175K - 200K", value: { min: "175", max: "200" } },
  { label: "Upto USD 200K - 250K", value: { min: "200", max: "250" } },
  { label: "Upto USD 250K - 300K", value: { min: "250", max: "300" } },
  { label: "Upto USD 300K - 500K", value: { min: "300", max: "500" } },
];

export const creativeHobbies = [
  "Writing",
  "Cooking",
  "Singing",
  "Photography",
  "Playing instruments",
  "Painting",
  "DIY crafts",
  "Dancing",
  "Acting",
  "Poetry",
  "Gardening",
  "Bloging",
  "Content creation",
  "Designing",
  "Doodling",
];

export const funs = [
  "Movies",
  "Music",
  "Traveling",
  "Reading",
  "Sports",
  "Social media",
  "Gaming",
  "Binge-watching",
  "Biking",
  "Clubbing",
  "Shopping",
  "Theater & Events",
  "Anime",
  "Stand ups",
];

export const fitness = [
  "Running",
  "Cycling",
  "Yoga",
  "Meditation",
  "Walking",
  "Working out",
];

export const otherInterests = [
  "Pets",
  "Foodie",
  "Vegan",
  "News & Politics",
  "Social service",
  "Enterpreneurship",
  "Home decor",
  "Investments",
];

export const countries = ["Bangladesh", "India", "Pakistan", "USA", "Canada"];

export const states = ["Dhaka", "Chittagong", "Sylet", "Khulna"];

export const colleges = [
  "University of Dhaka",
  "Bangladesh University of Engineering and Technology (BUET)",
  "University of Chittagong",
  "Jahangirnagar University",
  "Rajshahi University",
  "Khulna University",
  "Bangladesh Agricultural University",
  "Shahjalal University of Science and Technology (SUST)",
  "Dhaka University of Engineering and Technology (DUET)",
  "Islamic University, Bangladesh",
  "Comilla University",
  "Jatiya Kabi Kazi Nazrul Islam University",
  "Hajee Mohammad Danesh Science and Technology University",
  "Jessore University of Science and Technology",
  "Mawlana Bhashani Science and Technology University",
  "Noakhali Science and Technology University",
  "Pabna University of Science and Technology",
  "Patuakhali Science and Technology University",
  "Sher-e-Bangla Agricultural University",
  "Sylhet Agricultural University",
];

export const companies = [
  "Grameenphone IT",
  "Robi Axiata Limited",
  "Banglalink Digital Communications Ltd.",
  "Airtel Bangladesh Limited",
  "Huawei Technologies (Bangladesh) Ltd.",
  "Samsung Electronics Bangladesh Co. Ltd.",
  "Ovijat IT",
  "TechRepublic Bangladesh Ltd.",
  "BASIS (Bangladesh Association of Software and Information Services)",
  "DataSoft Systems Bangladesh Limited",
  "Eicra Soft Ltd.",
  "Brain Station 23 Ltd.",
  "Leads Corporation Limited",
  "SSL Wireless",
  "Ingenious Solutions",
  "Daffodil Computers Ltd.",
  "Synesis IT",
  "Amber IT Limited",
  "aamra companies",
  "Tiger IT Bangladesh Ltd.",
];

export const motherTongues2 = [
  "Mandarin (Putonghua)",
  "Hindi",
  "Bengali (Bangla)",
  "Indonesian (Bahasa Indonesia)",
  "Japanese",
  "Korean",
  "Thai (Siamese)",
  "Vietnamese",
  "Turkish",
  "Urdu",
  "Tagalog",
  "Arabic",
  "Malay/Indonesian",
  "Tamil",
  "Russian",
  "Farsi (Persian)",
  "Sinhala",
  "Nepali",
  "Burmese",
  "Khmer (Cambodian)",
  "Lao",
  "Mongolian",
  "Kazakh",
  "Uzbek",
  "Tajik",
  "Kyrgyz",
  "Turkmen",
];

export const bloodGroups = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];
