apiVersion: apps/v1
kind: Deployment
metadata:
  name: biyekorun-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: biyekorun-frontend
  template:
    metadata:
      labels:
        app: biyekorun-frontend
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: {{ .Values.limits.cpu }}
              memory: {{ .Values.limits.memory }}
            requests:
              cpu: {{ .Values.requests.cpu }}
              memory: {{ .Values.requests.memory }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}