apiVersion: v1
kind: Service
metadata:
  name: biyekorun-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: biyekorun-frontend
  type: NodePort
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
