# Default values for ts4u-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: biyekorun

# limits:
#   cpu: 1
#   memory: "2Gi"

# requests:
#   cpu: 1
#   memory: "2Gi"

limits:
  cpu: "750m"
  memory: "1Gi"

requests:
  cpu: "500m"
  memory: "512Mi"

host: biyekorun.us

image:
  name: biyekorun-frontend
  repository: ts4udocker/biyekorun-frontend
  tag: production-latest
  pullPolicy: IfNotPresent
imagePullSecrets:
  name: regcred