# Default values for ts4u-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: biyekorun-staging

limits:
  cpu: "500m"
  memory: "512Mi"

requests:
  cpu: "250m"
  memory: "256Mi"

host: staging.biyekorun.us
wwwHost: www.staging.biyekorun.us

hostSecret: biyekorun-tls-secret
hostWwwSecret: biyekorun-tls-secret

image:
  name: biyekorun-frontend
  repository: ts4udocker/biyekorun-frontend
  tag: staging-latest
  pullPolicy: IfNotPresent
imagePullSecrets:
  name: regcred